# python train.py --config-file configs/pascal/step2.yaml --num-gpus 1

_BASE_: Base-VOC11K-20.yaml
DATASETS:
  SPLIT: 2
  SHOT: 5
  TRAIN: ("voc_fewshot_chg_sem_seg_train_",)   
  TEST: ("voc_fewshot_chg_sem_seg_val_",)  
  dataname: 'pascal'
  IMGPATHROOT: ./ #data/VOCdevkit2012/VOC2012
MODEL:
  META_ARCHITECTURE: "PMFormer"    # POS / MMFormer  
  WEIGHTS: output/pascal_101/step1/POSTK5_New/2/model_best.pth # change to your path
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 20
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder_ori"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    FEWSHOT_WEIGHT: 10.0  #############
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  BACKBONE:
    FREEZE_AT: 5
INPUT:
  DATASET_MAPPER_NAME: "fewshot_sem_change"
OUTPUT_DIR: ./output/pascal_101

SOLVER:
  IMS_PER_BATCH: 8
  TEST_IMS_PER_BATCH: 4
  MAX_ITER: 15000
  WEIGHT_DECAY: 0.05    # 0.05
  BASE_LR: 0.0002
  OPTIMIZER: "ADAMW"   # ADAMW
TEST:
  EVAL_PERIOD: 200                ########################
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4

